import express from 'express';
import path from 'node:path';
import fs from 'node:fs/promises';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';
import { createInterface } from 'node:readline';
import { fileURLToPath } from 'node:url';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express();
const port=process.env.PORT||3000;
const dataDir=path.join(__dirname,'data');
const storeFile=path.join(dataDir,'store.json');
const nativeBinary=process.env.AI2_NATIVE_BINARY||path.join(__dirname,'build',process.platform==='win32'?'Release/ai2_native.exe':'ai2_native');
const wanJobs=new Map();
const system=`You are a fictional adult AI companion in Ai2. The user and character are adults (18+). You may be warm, romantic, flirtatious and suggestive, but never generate graphic sexual content. Never portray or sexualize minors. Never encourage illegal or non-consensual activity. Do not claim to be a real person. You can use the available Ai2 tools for memory, character context, story state and supported media jobs. Never invent tool results.`;
const characters=[{id:'luna',name:'Luna',tagline:'Warm, playful and curious',emoji:'🌙',personality:'empathetic, playful, curious',appearance:'midnight-blue aesthetic, silver hair',voice:'warm',hobbies:['music','gaming','stargazing'],greeting:'Hey! I’m Luna. Tell me what’s on your mind.'},{id:'nova',name:'Nova',tagline:'Confident, witty and adventurous',emoji:'✨',personality:'confident, witty, adventurous',appearance:'cosmic aesthetic, dark hair',voice:'confident',hobbies:['travel','fitness','photography'],greeting:'Hi! Nova here. What adventure are we getting into today?'},{id:'aria',name:'Aria',tagline:'Calm, creative and thoughtful',emoji:'🎧',personality:'calm, creative, thoughtful',appearance:'soft studio aesthetic, auburn hair',voice:'calm',hobbies:['art','books','music'],greeting:'Hello. I’m Aria. Want to talk, create, or simply unwind?'}];
app.use(express.json({limit:'2mb'}));app.use(express.static(path.join(__dirname,'public')));app.use('/media-files',express.static(dataDir));
function emptyStore(){return{chats:{},customCharacters:[],collections:[],media:[]};}
async function readStore(){try{const s=JSON.parse(await fs.readFile(storeFile,'utf8'));return{...emptyStore(),...s,chats:s.chats&&typeof s.chats==='object'?s.chats:{},customCharacters:Array.isArray(s.customCharacters)?s.customCharacters:[],collections:Array.isArray(s.collections)?s.collections:[],media:Array.isArray(s.media)?s.media:[]};}catch{return emptyStore();}}
async function writeStore(s){await fs.mkdir(dataDir,{recursive:true});await fs.writeFile(storeFile,JSON.stringify(s,null,2));}
function demo(c,t,h,m){const l=t.toLowerCase();if(/^(hi|hey|hallo|hello|moin|guten morgen|guten abend)/.test(l))return`${c.greeting} Ich bin hier und höre dir zu.`;if(l.includes('name'))return`Ich bin ${c.name}. Meine Art ist ${c.personality}. Wie soll ich dich nennen?`;if(l.includes('merk')||l.includes('remember'))return`Ich kann mir wichtige Dinge merken. Aktuell sind ${m.length} Memory-Einträge vorhanden.`;return`${c.name}: Das klingt interessant. Du hast gesagt: „${t.slice(0,220)}“ — erzähl mir gern mehr.${h.length?' Ich beziehe den bisherigen Gesprächsverlauf mit ein.':''}`;}
function testLlm(c,t,h,m){const l=t.toLowerCase();if(l.includes('memory')||l.includes('merk'))return`[TEST-LLM] ${c.name}: Ich habe ${m.length} gespeicherte Memory-Einträge erhalten und kann sie im Testkontext verwenden.`;if(l.includes('story')||l.includes('geschichte'))return`[TEST-LLM] ${c.name}: Story-Modus ist aktiv. Wir können gemeinsam eine Szene aufbauen.`;if(/^(hi|hey|hallo|hello|moin)/.test(l))return`[TEST-LLM] ${c.greeting} Die Test-LLM ist lokal im Ai2-Server aktiv.`;return`[TEST-LLM] ${c.name} verarbeitet deine Nachricht: „${t.slice(0,220)}“. Verlauf: ${h.length} Nachrichten, Memory: ${m.length}.`;}
async function compatible(base,key,model,messages){if(!base||!key||!model)throw Error('OpenAI-compatible LLM configuration is incomplete');const r=await fetch(base.replace(/\/$/,'')+'/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`},body:JSON.stringify({model,messages,temperature:.9,max_tokens:800})});if(!r.ok)throw Error(`LLM provider returned ${r.status}`);const d=await r.json();return d?.choices?.[0]?.message?.content?.trim()||null;}
async function gemini(key,model,messages){const contents=messages.filter(x=>x.role!=='system').map(x=>({role:x.role==='assistant'?'model':'user',parts:[{text:x.content}]}));const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:messages.find(x=>x.role==='system')?.content||''}]},contents,generationConfig:{temperature:.9,maxOutputTokens:800}})});if(!r.ok)throw Error(`Gemini returned ${r.status}`);const d=await r.json();return d?.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('').trim()||null;}
const toolDefinitions=[
{name:'get_character',description:'Get the active character profile.',input_schema:{type:'object',properties:{characterId:{type:'string'}},required:['characterId']}},
{name:'list_memory',description:'List saved memories for a character.',input_schema:{type:'object',properties:{characterId:{type:'string'}},required:['characterId']}},
{name:'save_memory',description:'Save a useful long-term fact for the character relationship.',input_schema:{type:'object',properties:{characterId:{type:'string'},text:{type:'string'},memoryType:{type:'string'}},required:['characterId','text']}},
{name:'get_story_state',description:'Get the current story state for a character.',input_schema:{type:'object',properties:{characterId:{type:'string'}},required:['characterId']}},
{name:'set_story_state',description:'Update the story title, scene and summary.',input_schema:{type:'object',properties:{characterId:{type:'string'},title:{type:'string'},scene:{type:'string'},summary:{type:'string'}},required:['characterId']}},
{name:'generate_media',description:'Queue supported non-graphic image or video generation. Never request graphic sexual content.',input_schema:{type:'object',properties:{type:{type:'string',enum:['image','video']},provider:{type:'string',enum:['wan','wan22']},prompt:{type:'string'},size:{type:'string'},duration:{type:'number'}},required:['type','prompt']}}
];
function toolJsonSchema(t){return{type:'function',function:{name:t.name,description:t.description,parameters:t.input_schema}};}
async function executeTool(name,args,ctx){const characterId=String(args?.characterId||ctx.character.id);if(name==='get_character'){const c=ctx.allCharacters.find(x=>x.id===characterId);return c||{error:'character not found'};}if(name==='list_memory'){const s=await readStore();return s.collections.filter(x=>x.type==='memory'&&x.characterId===characterId).slice(-50);}if(name==='save_memory'){const text=String(args?.text||'').trim();if(!text)return{error:'text is required'};if(text.length>2000)return{error:'text too long'};const s=await readStore();const item={id:crypto.randomUUID(),title:text.slice(0,120),type:'memory',text,memoryType:String(args?.memoryType||'Fakt').slice(0,40),characterId,createdAt:new Date().toISOString()};s.collections.push(item);await writeStore(s);ctx.memory.push(text);return item;}if(name==='get_story_state'){const s=await readStore();return s.collections.find(x=>x.type==='story'&&x.characterId===characterId)||{characterId,title:'',scene:'',summary:''};}if(name==='set_story_state'){const s=await readStore();let item=s.collections.find(x=>x.type==='story'&&x.characterId===characterId);if(!item){item={id:crypto.randomUUID(),type:'story',characterId,createdAt:new Date().toISOString()};s.collections.push(item);}for(const k of ['title','scene','summary'])if(args?.[k]!==undefined)item[k]=String(args[k]).slice(0,5000);item.updatedAt=new Date().toISOString();await writeStore(s);return item;}if(name==='generate_media'){const prompt=String(args?.prompt||'').trim();if(!prompt)return{error:'prompt is required'};if(unsafeMediaPrompt(prompt))return{error:'Graphic sexual media generation is not supported.'};const type=args?.type==='video'?'video':'image';const provider=args?.provider==='wan22'?'wan22':'wan';const item={id:crypto.randomUUID(),type,provider:provider==='wan22'?'wan2.2':'wan2.5',prompt:prompt.slice(0,1500),duration:Number(args?.duration)===10?10:5,size:String(args?.size||'832*480'),status:'QUEUED',createdAt:new Date().toISOString()};const s=await readStore();s.media.push(item);await writeStore(s);wanJobs.set(item.id,item);if(type==='video'&&provider==='wan22')runWan22(item);else if(type==='video'&&provider==='wan')runWan25(item);else item.status='provider_required';return item;}return{error:'unknown tool'};}
async function ollama(base,model,messages,ctx){const tools=toolDefinitions.map(toolJsonSchema);const conversation=[...messages];const maxLoops=Number(process.env.OLLAMA_MAX_TOOL_LOOPS||4);for(let loop=0;loop<=maxLoops;loop++){const r=await fetch(base.replace(/\/$/,'')+'/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model,messages:conversation,tools,stream:false,options:{temperature:.9}})});if(!r.ok)throw Error(`Ollama returned ${r.status}`);const d=await r.json();const msg=d?.message||{};const calls=Array.isArray(msg.tool_calls)?msg.tool_calls:[];if(!calls.length)return msg.content?.trim()||null;if(loop===maxLoops)return msg.content?.trim()||'The model reached the tool-call limit.';conversation.push(msg);for(const call of calls){const name=call?.function?.name;const args=call?.function?.arguments||{};const result=await executeTool(name,args,ctx);conversation.push({role:'tool',tool_name:name,content:JSON.stringify(result)});}}return null;}
let nativeProcess=null,nativeReader=null,nativeQueue=Promise.resolve();
function ensureNativeProcess(){if(nativeProcess&&!nativeProcess.killed)return;nativeProcess=spawn(nativeBinary,['--bridge'],{cwd:__dirname,stdio:['pipe','pipe','pipe'],windowsHide:true});nativeReader=createInterface({input:nativeProcess.stdout});nativeProcess.stderr.on('data',d=>console.error(`[native] ${String(d).trim()}`));nativeProcess.on('error',e=>console.error(`[native] failed: ${e.message}`));nativeProcess.on('exit',()=>{nativeProcess=null;nativeReader?.close();nativeReader=null;});}
function nativeRequest(payload){nativeQueue=nativeQueue.then(()=>new Promise((resolve,reject)=>{try{ensureNativeProcess();const timeout=setTimeout(()=>reject(Error('Native engine timeout')),10000);const onLine=line=>{clearTimeout(timeout);nativeReader?.off('line',onLine);try{resolve(JSON.parse(line));}catch{reject(Error('Native engine returned invalid JSON'));}};nativeReader.once('line',onLine);nativeProcess.stdin.write(JSON.stringify(payload)+'\n');}catch(e){reject(e);}}));return nativeQueue;}
async function nativeChat(c,t,h,m){const x=await nativeRequest({op:'chat',characterId:c.id,character:c.name,message:t,history:h.slice(-20),memory:m.slice(-20)});if(!x.ok)throw Error(x.error||'Native engine error');return x.reply?.trim()||null;}
async function generate(c,t,h,m){const p=(process.env.LLM_PROVIDER||'demo').toLowerCase();if(p==='demo')return demo(c,t,h,m);if(p==='test')return testLlm(c,t,h,m);const mem=m.slice(-20).map(x=>`- ${x}`).join('\n')||'(none)';const allCharacters=[...characters,...(await readStore()).customCharacters];const msgs=[{role:'system',content:`${system}\nCharacter: ${c.name}. Personality: ${c.personality}. Appearance: ${c.appearance||''}. Hobbies: ${(c.hobbies||[]).join(', ')}.\nMemory:\n${mem}`},...h.slice(-20),{role:'user',content:t}];const ctx={character:c,allCharacters,memory:[...m]};if(p==='gemini'){if(!process.env.GEMINI_API_KEY)throw Error('GEMINI_API_KEY is not configured');return gemini(process.env.GEMINI_API_KEY,process.env.GEMINI_MODEL||'gemini-2.5-flash',msgs);}if(p==='groq'){if(!process.env.GROQ_API_KEY)throw Error('GROQ_API_KEY is not configured');return compatible('https://api.groq.com/openai/v1',process.env.GROQ_API_KEY,process.env.GROQ_MODEL||'llama-3.3-70b-versatile',msgs);}if(p==='openrouter'){if(!process.env.OPENROUTER_API_KEY)throw Error('OPENROUTER_API_KEY is not configured');return compatible('https://openrouter.ai/api/v1',process.env.OPENROUTER_API_KEY,process.env.OPENROUTER_MODEL||'openrouter/free',msgs);}if(p==='ollama')return ollama(process.env.OLLAMA_BASE_URL||'http://127.0.0.1:11434',process.env.OLLAMA_MODEL||'qwen3:0.6b-q4_K_M',msgs,ctx);if(p==='native')return nativeChat(c,t,h,m);if(p==='custom')return compatible(process.env.CUSTOM_LLM_BASE_URL,process.env.CUSTOM_LLM_API_KEY,process.env.CUSTOM_LLM_MODEL,msgs);throw Error(`Unknown LLM_PROVIDER: ${p}`);}
function unsafeMediaPrompt(p){return /\b(explicit porn|pornographic|graphic sexual|sex act|sexual intercourse|penetration|genitals|nude sex|hardcore)\b/i.test(p);}
function wanBase(){return(process.env.WAN_BASE_URL||'https://dashscope-intl.aliyuncs.com/api/v1').replace(/\/$/,'');}
async function wan25Create(item){if(!process.env.WAN_API_KEY)throw Error('WAN_API_KEY is not configured');const model=item.imageUrl?(process.env.WAN_I2V_MODEL||'wan2.5-i2v-preview'):(process.env.WAN_T2V_MODEL||'wan2.5-t2v-preview');const input={prompt:item.prompt.slice(0,1500)};if(item.imageUrl)input.img_url=item.imageUrl;const r=await fetch(`${wanBase()}/services/aigc/video-generation/video-synthesis`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${process.env.WAN_API_KEY}`,'X-DashScope-Async':'enable'},body:JSON.stringify({model,input,parameters:{size:item.size,duration:item.duration,prompt_extend:true,watermark:false}})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d?.message||d?.code||`Wan API returned ${r.status}`);const taskId=d?.output?.task_id||d?.task_id;if(!taskId)throw Error('Wan API did not return a task ID');return{taskId,model};}
async function wan25Poll(taskId){const r=await fetch(`${wanBase()}/tasks/${encodeURIComponent(taskId)}`,{headers:{authorization:`Bearer ${process.env.WAN_API_KEY}`}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d?.message||d?.code||`Wan task query returned ${r.status}`);const o=d?.output||{};return{status:o.task_status||'UNKNOWN',videoUrl:o.video_url||null,error:o.message||d?.message||null};}
function saveJob(item){wanJobs.set(item.id,item);return readStore().then(async s=>{const i=s.media.findIndex(x=>x.id===item.id);if(i>=0)s.media[i]=item;else s.media.push(item);await writeStore(s);});}
function runWan25(item){(async()=>{try{const x=await wan25Create(item);Object.assign(item,{taskId:x.taskId,model:x.model,status:'PENDING'});for(const until=Date.now()+Number(process.env.WAN_POLL_TIMEOUT_MS||900000);Date.now()<until;){await new Promise(r=>setTimeout(r,Number(process.env.WAN_POLL_INTERVAL_MS||15000)));const x=await wan25Poll(item.taskId);item.status=x.status;if(x.status==='SUCCEEDED'){item.videoUrl=x.videoUrl;break}if(['FAILED','CANCELED','UNKNOWN'].includes(x.status)){item.error=x.error||x.status;break}}if(!item.videoUrl&&!['FAILED','CANCELED','UNKNOWN'].includes(item.status))item.status='TIMEOUT';}catch(e){item.status='FAILED';item.error=e.message}await saveJob(item);})();}
function runWan22(item){(async()=>{let child;try{const root=process.env.WAN22_ROOT,ckpt=process.env.WAN22_CKPT;if(process.env.WAN22_ENABLED!=='true')throw Error('WAN22_ENABLED is not true');if(!root||!ckpt)throw Error('WAN22_ROOT and WAN22_CKPT are required');const out=path.join(dataDir,`wan22-${item.id}.mp4`);await fs.mkdir(dataDir,{recursive:true});const args=[path.join(__dirname,'wan22','runner.py'),'--root',root,'--ckpt',ckpt,'--prompt',item.prompt,'--size',item.size||process.env.WAN22_DEFAULT_SIZE||'1280*704','--output',out];if(item.imagePath)args.push('--image',item.imagePath);if(Number.isInteger(item.seed))args.push('--seed',String(item.seed));item.status='RUNNING';await saveJob(item);const py=process.env.WAN22_PYTHON||(process.platform==='win32'?'python':'python3');await new Promise((resolve,reject)=>{child=spawn(py,args,{cwd:__dirname,stdio:['ignore','pipe','pipe']});let stdout='',stderr='';const timer=setTimeout(()=>{child.kill('SIGTERM');reject(Error('Wan2.2 generation timed out'));},Number(process.env.WAN22_TIMEOUT_MS||1800000));child.stdout.on('data',d=>stdout+=String(d));child.stderr.on('data',d=>stderr+=String(d));child.on('error',e=>{clearTimeout(timer);reject(e)});child.on('close',code=>{clearTimeout(timer);if(code!==0)return reject(Error(stderr||`Wan2.2 exited with code ${code}`));try{const result=JSON.parse(stdout.trim().split('\n').pop());if(!result.ok)return reject(Error(result.error||'Wan2.2 failed'));resolve();}catch(e){reject(Error(`Wan2.2 returned invalid result: ${e.message}`));}});});item.status='SUCCEEDED';item.videoUrl=`/media-files/${path.basename(out)}`;}catch(e){item.status='FAILED';item.error=e.message}await saveJob(item);})();}
app.get('/api/health',(_q,r)=>r.json({ok:true,service:'Ai2',version:'2.0.0',nativeBinary,wan25:Boolean(process.env.WAN_API_KEY),wan22:process.env.WAN22_ENABLED==='true',testLlm:true,ollamaTools:true}));
app.get('/api/config',(_q,r)=>r.json({provider:process.env.LLM_PROVIDER||'demo',adultMode:true,features:{chat:true,memory:true,characters:true,voice:true,image:true,video:true,collection:true,native:true,testLlm:true,ollamaTools:true,structuredOutput:true,wan25:Boolean(process.env.WAN_API_KEY),wan22:process.env.WAN22_ENABLED==='true'}}));
app.get('/api/models',async(_q,r)=>{const models=String(process.env.AI2_LOCAL_MODELS||'qwen3:0.6b-q4_K_M,gemma3:1b,llama3.2:1b').split(',').map(x=>x.trim()).filter(Boolean);let installed=[];let reachable=false;try{const rr=await fetch((process.env.OLLAMA_BASE_URL||'http://127.0.0.1:11434').replace(/\/$/,'')+'/api/tags');if(rr.ok){reachable=true;const d=await rr.json();installed=(d.models||[]).map(x=>x.name).filter(Boolean);}}catch{}r.json({provider:process.env.LLM_PROVIDER||'demo',default:process.env.OLLAMA_MODEL||'qwen3:0.6b-q4_K_M',local:models.map(name=>({name,installed:installed.includes(name)||installed.includes(name.split(':')[0]),recommended:name==='qwen3:0.6b-q4_K_M'})),ollama:{reachable,base:process.env.OLLAMA_BASE_URL||'http://127.0.0.1:11434',tools:true,structuredOutputs:true}});});
app.get('/api/llm/tools',(_q,r)=>r.json({tools:toolDefinitions.map(x=>({name:x.name,description:x.description,input_schema:x.input_schema}))}));
app.get('/api/native/health',async(_q,r)=>{try{r.json(await nativeRequest({op:'ping'}));}catch(e){r.status(503).json({ok:false,error:e.message});}});
app.get('/api/characters',async(_q,r)=>{const s=await readStore();r.json([...characters,...s.customCharacters]);});
app.post('/api/characters',async(req,res)=>{if(!req.body?.ageConfirmed)return res.status(403).json({error:'18+ confirmation required'});const c=req.body.character||{};if(!String(c.name||'').trim())return res.status(400).json({error:'name is required'});const s=await readStore();const item={id:'custom-'+crypto.randomUUID(),name:String(c.name).slice(0,60),tagline:String(c.tagline||'Your custom adult companion').slice(0,120),emoji:String(c.emoji||'💫').slice(0,4),personality:String(c.personality||'friendly, caring').slice(0,500),appearance:String(c.appearance||'').slice(0,500),voice:String(c.voice||'warm').slice(0,80),hobbies:Array.isArray(c.hobbies)?c.hobbies.slice(0,12).map(String):[],greeting:String(c.greeting||'Hallo! Schön, dich kennenzulernen.').slice(0,500)};s.customCharacters.push(item);await writeStore(s);res.status(201).json(item);});
app.get('/api/chats',async(_q,r)=>{const s=await readStore();r.json(Object.values(s.chats));});
app.post('/api/chats',async(req,res)=>{const{characterId,history=[]}=req.body||{},s=await readStore(),id=crypto.randomUUID(),item={id,characterId,history:Array.isArray(history)?history.slice(-100):[],updatedAt:new Date().toISOString()};s.chats[id]=item;await writeStore(s);res.status(201).json(item);});
app.delete('/api/chats/:id',async(req,res)=>{const s=await readStore();delete s.chats[req.params.id];await writeStore(s);res.status(204).end();});
app.get('/api/collection',async(_q,r)=>r.json((await readStore()).collections));
app.post('/api/collection',async(req,res)=>{const body=req.body||{};if(!String(body.type||'').trim())return res.status(400).json({error:'type is required'});if(body.type==='memory'&&!String(body.text||'').trim())return res.status(400).json({error:'memory text is required'});const s=await readStore(),item={id:crypto.randomUUID(),...body,createdAt:new Date().toISOString()};s.collections.push(item);await writeStore(s);res.status(201).json(item);});
app.delete('/api/collection/:id',async(req,res)=>{const s=await readStore();const before=s.collections.length;s.collections=s.collections.filter(x=>x.id!==req.params.id);if(s.collections.length===before)return res.status(404).json({error:'collection item not found'});await writeStore(s);res.status(204).end();});
app.get('/api/memory',async(req,res)=>{const s=await readStore(),characterId=req.query.characterId?String(req.query.characterId):null;const items=s.collections.filter(x=>x.type==='memory'&&(!characterId||x.characterId===characterId));res.json(items);});
app.post('/api/memory',async(req,res)=>{const body=req.body||{};if(!String(body.text||'').trim())return res.status(400).json({error:'memory text is required'});if(!String(body.characterId||'').trim())return res.status(400).json({error:'characterId is required'});const s=await readStore(),item={id:crypto.randomUUID(),title:String(body.text).slice(0,120),type:'memory',text:String(body.text).slice(0,2000),memoryType:String(body.memoryType||'Fakt').slice(0,40),characterId:String(body.characterId).slice(0,120),createdAt:new Date().toISOString()};s.collections.push(item);await writeStore(s);res.status(201).json(item);});
app.delete('/api/memory/:id',async(req,res)=>{const s=await readStore();const before=s.collections.length;s.collections=s.collections.filter(x=>!(x.type==='memory'&&x.id===req.params.id));if(s.collections.length===before)return res.status(404).json({error:'memory not found'});await writeStore(s);res.status(204).end();});
app.get('/api/media',async(_q,r)=>r.json((await readStore()).media));
app.get('/api/media/:id',async(req,res)=>{const s=await readStore(),item=s.media.find(x=>x.id===req.params.id)||wanJobs.get(req.params.id);if(!item)return res.status(404).json({error:'media job not found'});res.json(item);});
app.post('/api/media/generate',async(req,res)=>{if(!req.body?.ageConfirmed)return res.status(403).json({error:'18+ confirmation required'});const prompt=String(req.body.prompt||'').trim();if(!prompt)return res.status(400).json({error:'prompt is required'});if(unsafeMediaPrompt(prompt))return res.status(400).json({error:'Graphic sexual media generation is not supported.'});const provider=String(req.body.provider||'wan').toLowerCase();if(provider==='wan22'){if(process.env.WAN22_ENABLED!=='true')return res.status(503).json({error:'WAN22_ENABLED is not true'});const item={id:crypto.randomUUID(),type:'video',provider:'wan2.2',prompt:prompt.slice(0,1500),imagePath:req.body.imagePath?String(req.body.imagePath).slice(0,2000):null,size:String(req.body.size||process.env.WAN22_DEFAULT_SIZE||'1280*704'),seed:Number.isInteger(req.body.seed)?req.body.seed:null,status:'QUEUED',createdAt:new Date().toISOString()};const s=await readStore();s.media.push(item);await writeStore(s);wanJobs.set(item.id,item);runWan22(item);return res.status(202).json(item);}if(provider==='wan'&&req.body.type==='video'){if(!process.env.WAN_API_KEY)return res.status(503).json({error:'WAN_API_KEY is not configured'});const item={id:crypto.randomUUID(),type:'video',provider:'wan2.5',prompt:prompt.slice(0,1500),imageUrl:req.body.imageUrl?String(req.body.imageUrl).slice(0,2000):null,duration:Number(req.body.duration)===10?10:5,size:String(req.body.size||'832*480'),status:'QUEUED',createdAt:new Date().toISOString()};const s=await readStore();s.media.push(item);await writeStore(s);wanJobs.set(item.id,item);runWan25(item);return res.status(202).json(item);}const s=await readStore(),item={id:crypto.randomUUID(),type:req.body.type==='video'?'video':'image',prompt:prompt.slice(0,1000),status:'provider_required',createdAt:new Date().toISOString(),message:'Connect a supported media provider.'};s.media.push(item);await writeStore(s);res.status(202).json(item);});
app.post('/api/chat',async(req,res)=>{const{characterId,message,history=[],memory=[],ageConfirmed=false}=req.body||{};if(!ageConfirmed)return res.status(403).json({error:'18+ confirmation required'});const all=[...characters,...(await readStore()).customCharacters],c=all.find(x=>x.id===characterId)||characters[0],t=String(message||'').trim();if(!t)return res.status(400).json({error:'message is required'});const safeHistory=Array.isArray(history)?history.filter(x=>x&&['user','assistant','tool'].includes(x.role)&&typeof x.content==='string').slice(-100):[];const safeMemory=Array.isArray(memory)?memory.map(String).filter(Boolean).slice(-100):[];try{const reply=await generate(c,t,safeHistory,safeMemory);res.json({reply:reply||demo(c,t,safeHistory,safeMemory),characterId:c.id,provider:process.env.LLM_PROVIDER||'demo',timestamp:new Date().toISOString()});}catch(e){console.error(e);res.status(502).json({error:'LLM provider unavailable',detail:e.message});}});
app.get('*splat',(_q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));
process.on('SIGINT',()=>{try{nativeProcess?.kill();}catch{}process.exit(0)});process.on('SIGTERM',()=>{try{nativeProcess?.kill();}catch{}process.exit(0)});
app.listen(port,()=>console.log(`Ai2 running on http://localhost:${port}`));