import express from 'express';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(__dirname,'..');
const dataDir=path.join(root,'data');
const dbFile=path.join(dataDir,'payments.json');
const app=express();
const port=Number(process.env.AI2_PAYMENT_PORT||3020);
const secret=String(process.env.AI2_PAYMENT_SECRET||'').trim();
const adminToken=String(process.env.AI2_ADMIN_TOKEN||'').trim();
const stripeKey=String(process.env.STRIPE_SECRET_KEY||'').trim();
const webhookSecret=String(process.env.STRIPE_WEBHOOK_SECRET||'').trim();
const baseUrl=String(process.env.AI2_PAYMENT_BASE_URL||`http://127.0.0.1:${port}`).replace(/\/$/,'');
const successUrl=String(process.env.PAYMENT_SUCCESS_URL||'http://localhost:3000/?payment=success');
const cancelUrl=String(process.env.PAYMENT_CANCEL_URL||'http://localhost:3000/?payment=cancelled');
const publicCheckout=String(process.env.AI2_PAYMENT_PUBLIC_CHECKOUT||'false').toLowerCase()==='true';
const plans={plus:{name:'Ai2 Plus',amount:999,currency:'eur',interval:'month',stripePriceId:String(process.env.STRIPE_PRICE_PLUS||'').trim()},pro:{name:'Ai2 Pro',amount:1999,currency:'eur',interval:'month',stripePriceId:String(process.env.STRIPE_PRICE_PRO||'').trim()}};
const publicHits=new Map();
app.disable('x-powered-by');
app.use((req,res,next)=>{const origin=req.get('origin');if(origin&&origin===process.env.AI2_PAYMENT_ALLOWED_ORIGIN)res.setHeader('access-control-allow-origin',origin);res.setHeader('access-control-allow-methods','GET,POST,OPTIONS');res.setHeader('access-control-allow-headers','content-type,x-ai2-admin-token,x-ai2-payment-secret');if(req.method==='OPTIONS')return res.sendStatus(204);next();});
app.use('/api/payments/webhook',express.raw({type:'application/json',limit:'256kb'}));
app.use(express.json({limit:'64kb'}));
function empty(){return{customers:{},subscriptions:{},payments:{},events:{},refunds:{},audit:[]};}
async function readDb(){try{const x=JSON.parse(await fs.readFile(dbFile,'utf8'));return{...empty(),...x,audit:Array.isArray(x.audit)?x.audit:[]};}catch{return empty();}}
async function writeDb(db){await fs.mkdir(dataDir,{recursive:true});const tmp=`${dbFile}.${process.pid}.tmp`;await fs.writeFile(tmp,JSON.stringify(db,null,2),'utf8');await fs.rename(tmp,dbFile);}
function sameSecret(s,e){if(!s||!e)return false;const a=Buffer.from(String(s)),b=Buffer.from(String(e));return a.length===b.length&&crypto.timingSafeEqual(a,b);}
function auth(req,res,next){if(sameSecret(req.get('x-ai2-payment-secret'),secret))return next();if(sameSecret(req.get('x-ai2-admin-token'),adminToken))return next();return res.status(secret||adminToken?401:503).json({error:secret||adminToken?'payment/admin authentication required':'payment authentication is not configured'});}
function adminAuth(req,res,next){if(!adminToken)return res.status(503).json({error:'AI2_ADMIN_TOKEN is not configured'});if(!sameSecret(req.get('x-ai2-admin-token'),adminToken))return res.status(401).json({error:'admin authentication required'});next();}
function publicRateLimit(req,res,next){const key=req.ip||req.socket.remoteAddress||'unknown';const now=Date.now(),item=publicHits.get(key);if(!item||now-item.started>60000){publicHits.set(key,{started:now,count:1});return next();}item.count++;if(item.count>10)return res.status(429).json({error:'too many billing requests; try again later'});next();}
function stripeReady(){return Boolean(stripeKey);}
async function stripe(p,o={}){if(!stripeReady())throw Error('STRIPE_SECRET_KEY is not configured');const r=await fetch(`https://api.stripe.com/v1/${p}`,{...o,headers:{authorization:`Bearer ${stripeKey}`,'content-type':'application/x-www-form-urlencoded',...(o.headers||{})}});const text=await r.text();let d={};try{d=JSON.parse(text);}catch{}if(!r.ok)throw Error(d?.error?.message||`Stripe returned ${r.status}`);return d;}
function form(obj){const p=new URLSearchParams();for(const [k,v] of Object.entries(obj))if(v!==undefined&&v!==null)p.append(k,String(v));return p.toString();}
function planFor(id){const key=String(id||'').toLowerCase(),p=plans[key];return p?{id:key,...p}:null;}
function validUser(v){return String(v||'').trim().slice(0,120);}
function validEmail(v){const e=String(v||'').trim().toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)?e:null;}
function verifyStripeSignature(raw,header){if(!webhookSecret||!header)return false;let ts=null,v1=null;for(const part of String(header).split(',')){const [k,v]=part.split('=');if(k==='t')ts=v;if(k==='v1')v1=v;}if(!ts||!v1||Math.abs(Date.now()/1000-Number(ts))>300)return false;const expected=crypto.createHmac('sha256',webhookSecret).update(`${ts}.${raw.toString('utf8')}`).digest('hex');return sameSecret(expected,v1);}
function recordEvent(db,event){if(db.events[event.id])return false;db.events[event.id]={id:event.id,type:event.type,createdAt:new Date().toISOString()};return true;}
function audit(db,action,data={}){db.audit.push({id:crypto.randomUUID(),action,...data,createdAt:new Date().toISOString()});if(db.audit.length>2000)db.audit=db.audit.slice(-2000);}
async function createCheckout({userId,email,planId}){const user=validUser(userId),mail=validEmail(email),plan=planFor(planId);if(!user||!mail||!plan)throw Error('userId, email and a valid plan (plus/pro) are required');if(!plan.stripePriceId)throw Error(`Stripe price is not configured for ${plan.id}`);const db=await readDb();let customerId=db.customers[user]?.stripeCustomerId;if(!customerId){const c=await stripe('customers',{method:'POST',body:form({email:mail,'metadata[userId]':user})});customerId=c.id;db.customers[user]={userId:user,email:mail,stripeCustomerId:customerId,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await writeDb(db);}const body=form({'mode':'subscription','customer':customerId,'line_items[0][price]':plan.stripePriceId,'line_items[0][quantity]':'1','success_url':successUrl,'cancel_url':cancelUrl,'client_reference_id':user,'metadata[userId]':user,'metadata[planId]':plan.id,'subscription_data[metadata][userId]':user,'subscription_data[metadata][planId]':plan.id});const session=await stripe('checkout/sessions',{method:'POST',body});return{ok:true,id:session.id,url:session.url,plan:{id:plan.id,name:plan.name,amount:plan.amount,currency:plan.currency,interval:plan.interval}};}
function publicStatus(userId,db){const user=validUser(userId),subscriptions=Object.values(db.subscriptions).filter(x=>x.userId===user),active=subscriptions.find(x=>['active','trialing'].includes(x.status));return{userId:user,plan:active?.planId||'free',premium:Boolean(active),subscription:active||null};}
async function applyEvent(db,event){const o=event.data?.object||{};if(event.type==='checkout.session.completed'){const userId=validUser(o.metadata?.userId),planId=String(o.metadata?.planId||'').toLowerCase();if(userId){db.customers[userId]={...(db.customers[userId]||{}),userId,email:o.customer_details?.email||db.customers[userId]?.email||null,stripeCustomerId:o.customer||db.customers[userId]?.stripeCustomerId||null,updatedAt:new Date().toISOString()};db.payments[o.id]={id:o.id,userId,planId,mode:o.mode,status:o.payment_status||'completed',stripeCustomerId:o.customer||null,subscriptionId:o.subscription||null,paymentIntentId:o.payment_intent||null,amountTotal:o.amount_total||null,currency:o.currency||null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};if(o.subscription)db.subscriptions[o.subscription]={id:o.subscription,userId,planId,status:'active',stripeCustomerId:o.customer||null,updatedAt:new Date().toISOString()};audit(db,'checkout.completed',{userId,paymentId:o.id,planId});}}
else if(event.type.startsWith('customer.subscription.')){const sub=o,userId=validUser(sub.metadata?.userId)||Object.values(db.customers).find(x=>x.stripeCustomerId===sub.customer)?.userId;if(userId){db.subscriptions[sub.id]={id:sub.id,userId,planId:String(sub.metadata?.planId||'').toLowerCase(),status:sub.status,stripeCustomerId:sub.customer||null,currentPeriodEnd:sub.current_period_end?new Date(sub.current_period_end*1000).toISOString():null,cancelAtPeriodEnd:Boolean(sub.cancel_at_period_end),updatedAt:new Date().toISOString()};audit(db,`subscription.${sub.status}`,{userId,subscriptionId:sub.id});}}
else if(event.type==='invoice.paid'||event.type==='invoice.payment_failed'){const customerId=o.customer,userId=Object.values(db.customers).find(x=>x.stripeCustomerId===customerId)?.userId||validUser(o.metadata?.userId);if(userId){const id=o.id;db.payments[id]={...(db.payments[id]||{}),id,userId,invoiceId:id,stripeCustomerId:customerId||null,subscriptionId:o.subscription||null,paymentIntentId:o.payment_intent||null,status:event.type==='invoice.paid'?'paid':'failed',amountPaid:o.amount_paid||0,currency:o.currency||null,createdAt:new Date((o.created||Date.now()/1000)*1000).toISOString(),updatedAt:new Date().toISOString()};audit(db,event.type,{userId,paymentId:id});}}}
app.get('/health',(_req,res)=>res.json({ok:true,service:'Ai2 payment server',version:'1.3.0',stripeConfigured:stripeReady(),webhookConfigured:Boolean(webhookSecret),publicCheckout,plans:Object.fromEntries(Object.entries(plans).map(([k,v])=>[k,{name:v.name,amount:v.amount,currency:v.currency,interval:v.interval,configured:Boolean(v.stripePriceId)}]))}));
app.post('/api/payments/webhook',(req,res)=>{const raw=Buffer.isBuffer(req.body)?req.body:Buffer.from(JSON.stringify(req.body||{}));if(!verifyStripeSignature(raw,req.get('stripe-signature')))return res.status(400).json({error:'invalid webhook signature'});(async()=>{const event=JSON.parse(raw.toString('utf8'));const db=await readDb();if(!recordEvent(db,event))return res.json({received:true,duplicate:true});await applyEvent(db,event);await writeDb(db);res.json({received:true});})().catch(e=>res.status(500).json({error:e.message}));});
app.post('/api/payments/checkout',auth,async(req,res)=>{try{res.json(await createCheckout({userId:req.body?.userId,email:req.body?.email,planId:req.body?.plan}));}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/payments/status/:userId',auth,async(req,res)=>{const userId=validUser(req.params.userId),db=await readDb(),subscriptions=Object.values(db.subscriptions).filter(x=>x.userId===userId),active=subscriptions.find(x=>['active','trialing'].includes(x.status));res.json({userId,plan:active?.planId||'free',premium:Boolean(active),subscription:active||null,payments:Object.values(db.payments).filter(x=>x.userId===userId).slice(-20)});});
app.post('/api/payments/portal',auth,async(req,res)=>{try{const userId=validUser(req.body?.userId),customerId=(await readDb()).customers[userId]?.stripeCustomerId;if(!customerId)return res.status(404).json({error:'customer not found'});const configuration=String(process.env.STRIPE_PORTAL_CONFIGURATION_ID||'').trim(),body=form({customer:customerId,return_url:successUrl,...(configuration?{configuration}:{})}),session=await stripe('billing_portal/sessions',{method:'POST',body});res.json({ok:true,url:session.url});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/payments/admin/summary',adminAuth,async(_req,res)=>{const db=await readDb(),subs=Object.values(db.subscriptions),payments=Object.values(db.payments),refunds=Object.values(db.refunds);res.json({customers:Object.keys(db.customers).length,subscriptions:subs.length,active:subs.filter(x=>['active','trialing'].includes(x.status)).length,cancelled:subs.filter(x=>x.cancelAtPeriodEnd||['canceled','unpaid','past_due'].includes(x.status)).length,payments:payments.length,paid:payments.filter(x=>x.status==='paid'||x.status==='completed').length,failed:payments.filter(x=>x.status==='failed').length,refunds:refunds.length,refunded:refunds.filter(x=>x.status==='succeeded').length});});
app.get('/api/payments/admin/transactions',adminAuth,async(req,res)=>{const db=await readDb();let rows=[...Object.values(db.payments).map(x=>({...x,kind:'payment'})),...Object.values(db.refunds).map(x=>({...x,kind:'refund'}))].sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')));const q=String(req.query.q||'').trim().toLowerCase(),status=String(req.query.status||'').trim().toLowerCase(),kind=String(req.query.kind||'').trim().toLowerCase();if(q)rows=rows.filter(x=>[x.userId,x.id,x.invoiceId,x.paymentIntentId,x.subscriptionId,x.stripeCustomerId,x.planId].some(v=>String(v||'').toLowerCase().includes(q)));if(status)rows=rows.filter(x=>String(x.status||'').toLowerCase()===status);if(kind)rows=rows.filter(x=>x.kind===kind);res.json({transactions:rows.slice(0,500)});});
app.get('/api/payments/admin/audit',adminAuth,async(req,res)=>{const db=await readDb(),q=String(req.query.q||'').trim().toLowerCase();let rows=db.audit.slice().reverse();if(q)rows=rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q));res.json({audit:rows.slice(0,500)});});
app.post('/api/payments/admin/refund',adminAuth,async(req,res)=>{try{const paymentId=String(req.body?.paymentId||'').trim(),amount=req.body?.amount===''||req.body?.amount==null?null:Math.max(1,Math.floor(Number(req.body.amount))),reason=['duplicate','fraudulent','requested_by_customer'].includes(req.body?.reason)?req.body.reason:'requested_by_customer';if(amount!==null&&!Number.isFinite(amount))return res.status(400).json({error:'invalid refund amount'});const db=await readDb(),payment=db.payments[paymentId];if(!payment)return res.status(404).json({error:'payment not found'});if(!payment.paymentIntentId)return res.status(400).json({error:'no refundable Stripe PaymentIntent is recorded for this payment yet'});const already=Number(payment.refundedAmount)||0;if(amount!==null&&amount+already>Number(payment.amountPaid||payment.amountTotal||0))return res.status(400).json({error:'refund exceeds the recorded payment amount'});const body={payment_intent:payment.paymentIntentId,reason};if(amount!==null)body.amount=amount;const refund=await stripe('refunds',{method:'POST',body:form(body)});db.refunds[refund.id]={id:refund.id,paymentId,userId:payment.userId,paymentIntentId:payment.paymentIntentId,status:refund.status,amount:refund.amount,currency:refund.currency,reason:refund.reason||reason,createdAt:new Date().toISOString()};payment.refundedAmount=already+Number(refund.amount||0);payment.refundStatus=refund.status;payment.updatedAt=new Date().toISOString();audit(db,'refund.created',{userId:payment.userId,paymentId,refundId:refund.id,amount:refund.amount,status:refund.status});await writeDb(db);res.json({ok:true,refund});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/payments/admin/subscription/cancel',adminAuth,async(req,res)=>{try{const id=String(req.body?.subscriptionId||'').trim();const db=await readDb();const sub=db.subscriptions[id];if(!sub)return res.status(404).json({error:'subscription not found'});const updated=await stripe(`subscriptions/${encodeURIComponent(id)}`,{method:'POST',body:form({'cancel_at_period_end':'true'})});sub.cancelAtPeriodEnd=true;sub.status=updated.status||sub.status;sub.currentPeriodEnd=updated.current_period_end?new Date(updated.current_period_end*1000).toISOString():sub.currentPeriodEnd;sub.updatedAt=new Date().toISOString();audit(db,'subscription.cancel_at_period_end',{userId:sub.userId,subscriptionId:id});await writeDb(db);res.json({ok:true,subscription:updated});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/payments/admin/customers',adminAuth,async(_req,res)=>{const db=await readDb();const customers=Object.values(db.customers).map(c=>{const payments=Object.values(db.payments).filter(x=>x.userId===c.userId);const subs=Object.values(db.subscriptions).filter(x=>x.userId===c.userId);return{...c,paymentCount:payments.length,paidCount:payments.filter(x=>['paid','completed'].includes(x.status)).length,activeSubscription:subs.find(x=>['active','trialing'].includes(x.status))||null,totalPaid:payments.reduce((n,x)=>n+Number(x.amountPaid||x.amountTotal||0),0),totalRefunded:payments.reduce((n,x)=>n+Number(x.refundedAmount||0),0)};});res.json({customers});});
app.post('/api/payments/public/checkout',publicRateLimit,async(req,res)=>{if(!publicCheckout)return res.status(404).json({error:'public checkout is disabled'});try{res.json(await createCheckout({userId:req.body?.userId,email:req.body?.email,planId:req.body?.plan}));}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/payments/public/status/:userId',publicRateLimit,async(req,res)=>{if(!publicCheckout)return res.status(404).json({error:'public billing is disabled'});const db=await readDb();res.json(publicStatus(req.params.userId,db));});
app.listen(port,()=>console.log(`Ai2 payment server running on ${baseUrl}`));
