import express from 'express';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(__dirname,'..');
const dataDir=path.join(root,'data');
const dbFile=path.join(dataDir,'payments.json');
const app=express();
const port=Number(process.env.AI2_PAYMENT_PORT||3020);
const secret=String(process.env.AI2_PAYMENT_SECRET||'').trim();
const stripeKey=String(process.env.STRIPE_SECRET_KEY||'').trim();
const webhookSecret=String(process.env.STRIPE_WEBHOOK_SECRET||'').trim();
const baseUrl=String(process.env.AI2_PAYMENT_BASE_URL||`http://127.0.0.1:${port}`).replace(/\/$/,'');
const successUrl=String(process.env.PAYMENT_SUCCESS_URL||'http://localhost:3000/?payment=success');
const cancelUrl=String(process.env.PAYMENT_CANCEL_URL||'http://localhost:3000/?payment=cancelled');
const publicCheckout=String(process.env.AI2_PAYMENT_PUBLIC_CHECKOUT||'false').toLowerCase()==='true';
const plans={plus:{name:'Ai2 Plus',amount:999,currency:'eur',interval:'month',stripePriceId:String(process.env.STRIPE_PRICE_PLUS||'').trim()},pro:{name:'Ai2 Pro',amount:1999,currency:'eur',interval:'month',stripePriceId:String(process.env.STRIPE_PRICE_PRO||'').trim()}};
const publicHits=new Map();
app.disable('x-powered-by');
app.use(express.raw({type:'application/json',limit:'256kb'}));
function empty(){return{customers:{},subscriptions:{},payments:{},events:{}};}
async function readDb(){try{const x=JSON.parse(await fs.readFile(dbFile,'utf8'));return{...empty(),...x};}catch{return empty();}}
async function writeDb(db){await fs.mkdir(dataDir,{recursive:true});const tmp=`${dbFile}.${process.pid}.tmp`;await fs.writeFile(tmp,JSON.stringify(db,null,2),'utf8');await fs.rename(tmp,dbFile);}
function auth(req,res,next){if(!secret)return res.status(503).json({error:'AI2_PAYMENT_SECRET is not configured'});const supplied=String(req.get('x-ai2-payment-secret')||'');const a=Buffer.from(supplied),b=Buffer.from(secret);if(!supplied||a.length!==b.length||!crypto.timingSafeEqual(a,b))return res.status(401).json({error:'payment server authentication required'});next();}
function publicRateLimit(req,res,next){const key=req.ip||req.socket.remoteAddress||'unknown';const now=Date.now(),windowMs=60000,max=10;const item=publicHits.get(key);if(!item||now-item.started>windowMs){publicHits.set(key,{started:now,count:1});return next();}item.count++;if(item.count>max)return res.status(429).json({error:'too many billing requests; try again later'});next();}
function stripeReady(){return Boolean(stripeKey);}
async function stripe(pathname,options={}){if(!stripeReady())throw Error('STRIPE_SECRET_KEY is not configured');const r=await fetch(`https://api.stripe.com/v1/${pathname}`,{...options,headers:{authorization:`Bearer ${stripeKey}`,'content-type':'application/x-www-form-urlencoded',...(options.headers||{})}});const text=await r.text();let d={};try{d=JSON.parse(text);}catch{}if(!r.ok)throw Error(d?.error?.message||`Stripe returned ${r.status}`);return d;}
function form(obj){const p=new URLSearchParams();for(const [k,v] of Object.entries(obj))if(v!==undefined&&v!==null)p.append(k,String(v));return p.toString();}
function planFor(id){const key=String(id||'').toLowerCase();const p=plans[key];return p?{id:key,...p}:null;}
function validUser(v){return String(v||'').trim().slice(0,120);}
function validEmail(v){const e=String(v||'').trim().toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)?e:null;}
function verifyStripeSignature(raw,header){if(!webhookSecret||!header)return false;let ts=null,v1=null;for(const part of String(header).split(',')){const [k,v]=part.split('=');if(k==='t')ts=v;if(k==='v1')v1=v;}if(!ts||!v1||Math.abs(Date.now()/1000-Number(ts))>300)return false;const expected=crypto.createHmac('sha256',webhookSecret).update(`${ts}.${raw.toString('utf8')}`).digest('hex');const a=Buffer.from(expected),b=Buffer.from(v1);return a.length===b.length&&crypto.timingSafeEqual(a,b);}
function recordEvent(db,event){if(db.events[event.id])return false;db.events[event.id]={id:event.id,type:event.type,createdAt:new Date().toISOString()};return true;}
async function createCheckout({userId,email,planId}){const user=validUser(userId),mail=validEmail(email),plan=planFor(planId);if(!user||!mail||!plan)throw Error('userId, email and a valid plan (plus/pro) are required');if(!plan.stripePriceId)throw Error(`Stripe price is not configured for ${plan.id}`);const db=await readDb();let customerId=db.customers[user]?.stripeCustomerId;if(!customerId){const c=await stripe('customers',{method:'POST',body:form({email:mail,'metadata[userId]':user})});customerId=c.id;db.customers[user]={userId:user,email:mail,stripeCustomerId:customerId,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await writeDb(db);}const body=form({'mode':'subscription','customer':customerId,'line_items[0][price]':plan.stripePriceId,'line_items[0][quantity]':'1','success_url':successUrl,'cancel_url':cancelUrl,'client_reference_id':user,'metadata[userId]':user,'metadata[planId]':plan.id,'subscription_data[metadata][userId]':user,'subscription_data[metadata][planId]':plan.id});const session=await stripe('checkout/sessions',{method:'POST',body});return{ok:true,id:session.id,url:session.url,plan:{id:plan.id,name:plan.name,amount:plan.amount,currency:plan.currency,interval:plan.interval}};}
function publicStatus(userId,db){const user=validUser(userId);const subscriptions=Object.values(db.subscriptions).filter(x=>x.userId===user);const active=subscriptions.find(x=>['active','trialing'].includes(x.status));return{userId:user,plan:active?.planId||'free',premium:Boolean(active),subscription:active||null};}
app.get('/health',(_req,res)=>res.json({ok:true,service:'Ai2 payment server',version:'1.1.0',stripeConfigured:stripeReady(),webhookConfigured:Boolean(webhookSecret),publicCheckout,plans:Object.fromEntries(Object.entries(plans).map(([k,v])=>[k,{name:v.name,amount:v.amount,currency:v.currency,interval:v.interval,configured:Boolean(v.stripePriceId)}]))}));
app.post('/api/payments/webhook',(req,res)=>{const raw=Buffer.isBuffer(req.body)?req.body:Buffer.from(JSON.stringify(req.body||{}));if(!verifyStripeSignature(raw,req.get('stripe-signature')))return res.status(400).json({error:'invalid webhook signature'});(async()=>{const event=JSON.parse(raw.toString('utf8'));const db=await readDb();if(!recordEvent(db,event))return res.json({received:true,duplicate:true});const o=event.data?.object||{};if(event.type==='checkout.session.completed'){const userId=validUser(o.metadata?.userId),planId=String(o.metadata?.planId||'').toLowerCase();if(userId){db.customers[userId]={userId,email:o.customer_details?.email||null,stripeCustomerId:o.customer||null,updatedAt:new Date().toISOString()};db.payments[o.id]={id:o.id,userId,planId,mode:o.mode,status:'completed',stripeCustomerId:o.customer||null,subscriptionId:o.subscription||null,amountTotal:o.amount_total||null,currency:o.currency||null,createdAt:new Date().toISOString()};if(o.subscription)db.subscriptions[o.subscription]={id:o.subscription,userId,planId,status:'active',stripeCustomerId:o.customer||null,updatedAt:new Date().toISOString()};}}else if(event.type.startsWith('customer.subscription.')){const sub=o,userId=validUser(sub.metadata?.userId)||Object.values(db.customers).find(x=>x.stripeCustomerId===sub.customer)?.userId;if(userId)db.subscriptions[sub.id]={id:sub.id,userId,planId:String(sub.metadata?.planId||'').toLowerCase(),status:sub.status,stripeCustomerId:sub.customer||null,currentPeriodEnd:sub.current_period_end?new Date(sub.current_period_end*1000).toISOString():null,cancelAtPeriodEnd:Boolean(sub.cancel_at_period_end),updatedAt:new Date().toISOString()};}await writeDb(db);res.json({received:true});})().catch(e=>res.status(500).json({error:e.message}));});
app.use(express.json({limit:'64kb'}));
app.post('/api/payments/checkout',auth,async(req,res)=>{try{res.json(await createCheckout({userId:req.body?.userId,email:req.body?.email,planId:req.body?.plan}));}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/payments/status/:userId',auth,async(req,res)=>{const userId=validUser(req.params.userId);const db=await readDb();const subscriptions=Object.values(db.subscriptions).filter(x=>x.userId===userId);const active=subscriptions.find(x=>['active','trialing'].includes(x.status));res.json({userId,plan:active?.planId||'free',premium:Boolean(active),subscription:active||null,payments:Object.values(db.payments).filter(x=>x.userId===userId).slice(-20)});});
app.post('/api/payments/portal',auth,async(req,res)=>{try{const userId=validUser(req.body?.userId),customerId=(await readDb()).customers[userId]?.stripeCustomerId;if(!customerId)return res.status(404).json({error:'customer not found'});const configuration=String(process.env.STRIPE_PORTAL_CONFIGURATION_ID||'').trim();const body=form({customer:customerId,return_url:successUrl,...(configuration?{configuration}:{})});const session=await stripe('billing_portal/sessions',{method:'POST',body});res.json({ok:true,url:session.url});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/payments/admin/summary',auth,async(_req,res)=>{const db=await readDb(),subs=Object.values(db.subscriptions);res.json({customers:Object.keys(db.customers).length,subscriptions:subs.length,active:subs.filter(x=>['active','trialing'].includes(x.status)).length,cancelled:subs.filter(x=>x.cancelAtPeriodEnd||['canceled','unpaid','past_due'].includes(x.status)).length,payments:Object.keys(db.payments).length});});
app.post('/api/payments/public/checkout',publicRateLimit,async(req,res)=>{if(!publicCheckout)return res.status(404).json({error:'public checkout is disabled'});try{res.json(await createCheckout({userId:req.body?.userId,email:req.body?.email,planId:req.body?.plan}));}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/payments/public/status/:userId',publicRateLimit,async(req,res)=>{if(!publicCheckout)return res.status(404).json({error:'public billing is disabled'});const db=await readDb();res.json(publicStatus(req.params.userId,db));});
app.listen(port,()=>console.log(`Ai2 payment server running on ${baseUrl}`));
